server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/startrip
    username: startrip
    password: startrip
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        type: trace
    hibernate:
      ddl-auto: update              # none,create,update,validate

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace